name: Release Local Agent

# Se activa cuando tag con el formato
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      # Descarga código del repositorio al tag
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura entorno de Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Cachea dependencias npm
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: local-agent/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('local-agent/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Instala dependencias del agente
      - name: Install dependencies
        run: npm install
        working-directory: ./local-agent

      # Compila aplicación y crea el .exe
      - name: Build application
        run: npm run build:prod
        working-directory: ./local-agent
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_URL: ${{ secrets.SERVER_URL }}